### ISSUE TITLE
[FE] 메인화면 구성하기 

### ISSUE THREAD

**Issue by choisohyun** [codesquad-member-2020/airbnb-08#10]
### 기능

[ Main ]

- [x]  FilterButton과 Accommodation 컴포넌트 불러오기
- [x]  스타일적용
- [x]  검색결과 제목 

[ FilterButton ]

- [x]  스타일 적용

[ Accommodation ]

- [x]  스타일 적용
- [x]  Badge, Image, Country, Rating, Title, Original Price, Price, Total Price, ReservationButton

**Comment by hyewon3938** [comment]
- 메인화면 스타일 적용 완료 

<img width="825" alt="에어비엔비화면" src="https://user-images.githubusercontent.com/58355499/82555321-8402ba80-9ba2-11ea-8001-025f0f12924b.png">
