### ISSUE TITLE
[FE] 컴포넌트 설계

### ISSUE THREAD

**Issue by choisohyun** [codesquad-member-2020/airbnb-08#9]
### 기능

- 컴포넌트 구조 설계하고 리액트 기본 틀로 작성하기 
- 컴포넌트 구조는 한 이후에 댓글로 남겨놓기

**Comment by hyewon3938** [comment]
- 컴포넌트 설계도

![](https://postfiles.pstatic.net/MjAyMDA1MjBfMTk0/MDAxNTg5OTYwMjA3NTI2.k3Ce6p4QBYGzTox6jd_kuFNuYg5U9mzy1KFtM267zbgg.i33GIgK21kowuUwo7vA_xOCfJQtFqKCgrGkVp6B0Ubwg.PNG.ehak3/%EC%97%90%EC%96%B4%EB%B9%84%EC%95%A4%EB%B9%84_%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8_%EC%84%A4%EA%B3%84.png?type=w580)
